export const closedFeelingGallery = [
    {
        img: "./closed/19.jpg",
        title: 'thirdlook',
        author: '',
        cols: 4,
    },
    {
        img: "./closed/20.jpg",
        title: 'thirdlook',
        author: '',
        cols: 4,
    },
    {
        img: "./closed/21.jpg",
        title: 'seventhlook',
        author: '',
        cols: 4,
    },
    {
        img: "./closed/23.jpg",
        title: 'fourthlook',
        author: '',
        cols: 4,
    },
    {
        img: "./closed/24.jpg",
        title: 'thirdlook',
        author: '',
        cols: 4,
    },
    {
        img: "./closed/25.jpg",
        title: 'seventhlook',
        author: '',
        cols: 4,
    },
    {
        img: "./closed/42.jpg",
        title: 'seventhlook',
        author: '',
        cols: 12,
        rows: 2,
    },
    {
        img: "./closed/22.jpg",
        title: 'thirdlook',
        author: '',
        cols: 8,
    },
    {
        img: "./closed/27.jpg",
        title: 'fourthlook',
        author: '',
        cols: 4,
    },
    {
        img: "./closed/29.jpg",
        title: 'thirdlook',
        author: '',
        cols: 8,
    },
    {
        img: "./closed/30.jpg",
        title: 'fourthlook',
        author: '',
        cols: 4,
    },
    {
        img: "./closed/6.png",
        title: 'thirdlook',
        author: '',
        cols: 12,
    },
    {
        img: "./closed/7.png",
        title: 'thirdlook',
        author: '',
        cols: 12,
    },
    {
        img: "./closed/33.jpg",
        title: 'fourthlook',
        author: '',
        cols: 6,
    },
    {
        img: "./closed/34.jpg",
        title: 'fourthlook',
        author: '',
        cols: 6,
    },
    {
        img: "./closed/37.jpg",
        title: 'fourthlook',
        author: '',
        cols: 6,
    },
    {
        img: "./closed/38.jpg",
        title: 'fourthlook',
        author: '',
        cols: 6,
    },
    {
        img: "./closed/41.jpg",
        title: 'seventhlook',
        author: '',
        cols: 12,
    },
]

export const closedFeelingGallery2 = [
    {
        img: "./closed/43.jpg",
        title: 'seventhlook',
        author: '',
        cols: 12,
        rows: 2,
    },
    {
        img: "./closed/13.jpg",
        title: 'seventhlook',
        author: '',
        cols: 3,
    },
    {
        img: "./closed/16.jpg",
        title: 'fourthlook',
        author: '',
        cols: 3,
    },
    {
        img: "./closed/17.jpg",
        title: 'seventhlook',
        author: '',
        cols: 3,
    },
    {
        img: "./closed/15.jpg",
        title: 'thirdlook',
        author: '',
        cols: 3,
    },
    {
        img: "./closed/13.jpg",
        title: 'seventhlook',
        author: '',
        cols: 6,
    },
    {
        img: "./closed/14.jpg",
        title: 'seventhlook',
        author: '',
        cols: 6,
    },
    {
        img: "./closed/31.jpg",
        title: 'fourthlook',
        author: '',
        cols: 12,
    },
    {
        img: "./closed/28.jpg",
        title: 'seventhlook',
        author: '',
        cols: 8,
    },
    {
        img: "./closed/32.jpg",
        title: 'seventhlook',
        author: '',
        cols: 4,
    },
    {
        img: "./closed/10.png",
        title: 'thirdlook',
        author: '',
        cols: 4,
    },
    {
        img: "./closed/2.png",
        title: 'thirdlook',
        author: '',
        cols: 4,
    },
    {
        img: "./closed/3.png",
        title: 'seventhlook',
        author: '',
        cols: 4,
    },
    {
        img: "./closed/4.png",
        title: 'fourthlook',
        author: '',
        cols: 4,
    },
    {
        img: "./closed/5.png",
        title: 'thirdlook',
        author: '',
        cols: 4,
    },
    {
        img: "./closed/8.png",
        title: 'seventhlook',
        author: '',
        cols: 4,
    },
    {
        img: "./closed/35.jpg",
        title: 'fourthlook',
        author: '',
        cols: 6,
    },
    {
        img: "./closed/36.jpg",
        title: 'fourthlook',
        author: '',
        cols: 6,
    },
    {
        img: "./closed/39.jpg",
        title: 'fourthlook',
        author: '',
        cols: 6,
    },
    {
        img: "./closed/40.jpg",
        title: 'fourthlook',
        author: '',
        cols: 6,
    },
    {
        img: "./closed/44.jpg",
        title: 'seventhlook',
        author: '',
        cols: 12,
    },
]