export const consumedGallery = [
    {
        id: '1',
        img: "./consumed/3.jpg",
        title: 'thirdlook',
        author: '',
        cols: 3,
    },
    {
        id: '2',
        img: "./consumed/15.jpg",
        title: 'thirdlook',
        author: '',
        cols: 3,
    },
    {
        id: '3',
        img: "./consumed/18.jpg",
        title: 'seventhlook',
        author: '',
        cols: 6,
    },
    {
        id: '4',
        img: "./consumed/26.jpg",
        title: 'fourthlook',
        author: '',
        cols: 6,
    },
    {
        id: '5',
        img: "./consumed/7.jpg",
        title: 'thirdlook',
        author: '',
        cols: 3,
    },
    {
        id: '6',
        img: "./consumed/2.jpg",
        title: 'seventhlook',
        author: '',
        cols: 3,
    },
    {
        id: '7',
        img: "./consumed/10.jpg",
        title: 'seventhlook',
        author: '',
        cols: 12,
        rows: 2,
    },
    {
        id: '8',
        img: "./consumed/25.jpg",
        title: 'thirdlook',
        author: '',
        cols: 8,
        rows: 1,
    },
    {
        id: '9',
        img: "./consumed/12.jpg",
        title: 'fourthlook',
        author: '',
        cols: 4,
    },
    {
        id: '10',
        img: "./consumed/23.jpg",
        title: 'thirdlook',
        author: '',
        cols: 12,
    },
    {
        id: '11',
        img: "./consumed/29.jpg",
        title: 'thirdlook',
        author: '',
        cols: 8,
    },
    {
        id: '12',
        img: "./consumed/30.jpg",
        title: 'fourthlook',
        author: '',
        cols: 4,
    },
]

export const consumedGallery2 = [
    {
        id: '13',
        img: "./consumed/24.jpg",
        title: 'seventhlook',
        author: '',
        cols: 12,
        rows: 2,
    },
    {
        id: '14',
        img: "./consumed/21.jpg",
        title: 'seventhlook',
        author: '',
        cols: 3,
    },
    {
        id: '15',
        img: "./consumed/16.jpg",
        title: 'fourthlook',
        author: '',
        cols: 3,
    },
    {
        id: '16',
        img: "./consumed/17.jpg",
        title: 'seventhlook',
        author: '',
        cols: 3,
    },
    {
        id: '17',
        img: "./consumed/11.jpg",
        title: 'thirdlook',
        author: '',
        cols: 3,
    },
    {
        id: '18',
        img: "./consumed/13.jpg",
        title: 'seventhlook',
        author: '',
        cols: 6,
    },
    {
        id: '19',
        img: "./consumed/14.jpg",
        title: 'seventhlook',
        author: '',
        cols: 6,
    },
    {
        id: '20',
        img: "./consumed/31.jpg",
        title: 'fourthlook',
        author: '',
        cols: 12,
    },
    {
        id: '21',
        img: "./consumed/32.jpg",
        title: 'seventhlook',
        author: '',
        cols: 4,
    },
    {
        id: '22',
        img: "./consumed/33.jpg",
        title: 'seventhlook',
        author: '',
        cols: 8,
    },
    {
        id: '23',
        img: "./consumed/28.jpg",
        title: 'seventhlook',
        author: '',
        cols: 8,
    },
    {
        id: '24',
        img: "./consumed/27.jpg",
        title: 'seventhlook',
        author: '',
        cols: 4,
    },
]