export const fearGeneration = [
    {
        id: '1',
        img: "./feargen/raf14.jpg",
        title: 'firstlook',
        author: '',
        cols: 2,
        key: 1,
    },
    {
        id: '2',
        img: "./feargen/raf19.jpg",
        title: 'firstlook',
        author: '',
        cols: 2,
    },
    {
        id: '3',
        img: "./feargen/raf20.jpg",
        title: 'firstlook',
        author: '',
        cols: 2,
    },
    {
        id: '4',
        img: "./feargen/lookbook.jpg",
        title: 'firstlook',
        author: '',
        cols: 6,
        rows: 1,
    },
    {
        id: '5',
        img: "./feargen/raf1.jpg",
        title: 'firstlook',
        author: '',
        cols: 6,
    },
    {
        id: '6',
        img: "./feargen/raf17.jpg",
        title: 'firstlook',
        author: '',
        cols: 3,
    },
    {
        id: '7',
        img: "./feargen/raf02.jpg",
        title: 'firstlook',
        author: '',
        cols: 3,
    },
    {
        id: '8',
        img: "./feargen/raf18.jpg",
        title: 'firstlook',
        author: '',
        cols: 2,
        rows: 1,
    },
    {
        id: '9',
        img: "./feargen/raf3.jpg",
        title: 'firstlook',
        author: '',
        cols: 10,
        rows: 1,
    },
    {
        id: '10',
        img: "./feargen/raf06.jpg",
        title: 'firstlook',
        author: '',
        cols: 2,
    },
    {
        id: '11',
        img: "./feargen/raf07.jpg",
        title: 'firstlook',
        author: '',
        cols: 2,
    },
    {
        id: '12',
        img: "./feargen/raf16.jpg",
        title: 'firstlook',
        author: '',
        cols: 2,
    },
    {
        id: '13',
        img: "./feargen/raf05.jpg",
        title: 'firstlook',
        author: '',
        cols: 2,
    },

    {
        id: '14',
        img: "./feargen/raf09.jpg",
        title: 'firstlook',
        author: '',
        cols: 2,
    },
    {
        id: '15',
        img: "./feargen/raf10.jpg",
        title: 'firstlook',
        author: '',
        cols: 2,
    },
    {
        id: '16',
        img: "./feargen/raf02.jpg",
        title: 'firstlook',
        author: '',
        cols: 2,
    },
    {
        id: '17',
        img: "./feargen/raf03.jpg",
        title: 'firstlook',
        author: '',
        cols: 2,
    },
    {
        id: '18',
        img: "./feargen/raf01.jpg",
        title: 'firstlook',
        author: '',
        cols: 2,
    },
    {
        id: '19',
        img: "./feargen/raf23.jpg",
        title: 'firstlook',
        author: '',
        cols: 6,
    },
    {
        id: '20',
        img: "./feargen/raf08.jpg",
        title: 'firstlook',
        author: '',
        cols: 4,
    },
    {
        id: '21',
        img: "./feargen/raf04.jpg",
        title: 'firstlook',
        author: '',
        cols: 4,
    },
    {
        id: '22',
        img: "./feargen/raf11.jpg",
        title: 'firstlook',
        author: '',
        cols: 4,
    },
    {
        id: '23',
        img: "./feargen/raf12.jpg",
        title: 'firstlook',
        author: '',
        cols: 2,
    },
    {
        id: '24',
        img: "./feargen/raf13.jpg",
        title: 'firstlook',
        author: '',
        cols: 4,
    },
    {
        id: '25',
        img: "./feargen/raf15.jpg",
        title: 'firstlook',
        author: '',
        cols: 2,
    },
    {
        id: '26',
        img: "./feargen/raf21.jpg",
        title: 'firstlook',
        author: '',
        cols: 4,
    },

];

