export const fearGeneration = [
    {
        img: "./feargen/raf14.jpg",
        title: 'firstlook',
        author: '',
        cols: 2,
    },
    {
        img: "./feargen/raf19.jpg",
        title: 'firstlook',
        author: '',
        cols: 2,
    },
    {
        img: "./feargen/raf20.jpg",
        title: 'firstlook',
        author: '',
        cols: 2,
    },
    {
        img: "./feargen/lookbook.jpg",
        title: 'firstlook',
        author: '',
        cols: 6,
        rows: 1,
    },
    {
        img: "./feargen/raf1.jpg",
        title: 'firstlook',
        author: '',
        cols: 6,
    },
    {
        img: "./feargen/raf17.jpg",
        title: 'firstlook',
        author: '',
        cols: 3,
    },
    {
        img: "./feargen/raf02.jpg",
        title: 'firstlook',
        author: '',
        cols: 3,
    },
    {
        img: "./feargen/raf18.jpg",
        title: 'firstlook',
        author: '',
        cols: 2,
        rows: 1,
    },
    {
        img: "./feargen/raf3.jpg",
        title: 'firstlook',
        author: '',
        cols: 10,
        rows: 1,
    },
    {
        img: "./feargen/raf06.jpg",
        title: 'firstlook',
        author: '',
        cols: 2,
    },
    {
        img: "./feargen/raf07.jpg",
        title: 'firstlook',
        author: '',
        cols: 2,
    },
    {
        img: "./feargen/raf16.jpg",
        title: 'firstlook',
        author: '',
        cols: 2,
    },
    {
        img: "./feargen/raf05.jpg",
        title: 'firstlook',
        author: '',
        cols: 2,
    },

    {
        img: "./feargen/raf09.jpg",
        title: 'firstlook',
        author: '',
        cols: 2,
    },
    {
        img: "./feargen/raf10.jpg",
        title: 'firstlook',
        author: '',
        cols: 2,
    },
    {
        img: "./feargen/raf02.jpg",
        title: 'firstlook',
        author: '',
        cols: 2,
    },
    {
        img: "./feargen/raf03.jpg",
        title: 'firstlook',
        author: '',
        cols: 2,
    },
    {
        img: "./feargen/raf01.jpg",
        title: 'firstlook',
        author: '',
        cols: 2,
    },
    {
        img: "./feargen/raf23.jpg",
        title: 'firstlook',
        author: '',
        cols: 6,
    },
    {
        img: "./feargen/raf08.jpg",
        title: 'firstlook',
        author: '',
        cols: 4,
    },
    {
        img: "./feargen/raf04.jpg",
        title: 'firstlook',
        author: '',
        cols: 4,
    },
    {
        img: "./feargen/raf11.jpg",
        title: 'firstlook',
        author: '',
        cols: 4,
    },
    {
        img: "./feargen/raf12.jpg",
        title: 'firstlook',
        author: '',
        cols: 2,
    },
    {
        img: "./feargen/raf13.jpg",
        title: 'firstlook',
        author: '',
        cols: 4,
    },
    {
        img: "./feargen/raf15.jpg",
        title: 'firstlook',
        author: '',
        cols: 2,
    },
    {
        img: "./feargen/raf21.jpg",
        title: 'firstlook',
        author: '',
        cols: 4,
    },

];

