export const closedFeelingGallery = [
    {
        id: '1',
        img: "./closed/19.jpg",
        title: 'thirdlook',
        author: '',
        cols: 4,
    },
    {
        id: '2',
        img: "./closed/20.jpg",
        title: 'thirdlook',
        author: '',
        cols: 4,
    },
    {
        id: '3',
        img: "./closed/21.jpg",
        title: 'seventhlook',
        author: '',
        cols: 4,
    },
    {
        id: '4',
        img: "./closed/23.jpg",
        title: 'fourthlook',
        author: '',
        cols: 4,
    },
    {
        id: '5',
        img: "./closed/24.jpg",
        title: 'thirdlook',
        author: '',
        cols: 4,
    },
    {
        id: '6',
        img: "./closed/25.jpg",
        title: 'seventhlook',
        author: '',
        cols: 4,
    },
    {
        id: '7',
        img: "./closed/42.jpg",
        title: 'seventhlook',
        author: '',
        cols: 12,
        rows: 2,
    },
    {
        id: '8',
        img: "./closed/22.jpg",
        title: 'thirdlook',
        author: '',
        cols: 8,
    },
    {
        id: '9',
        img: "./closed/27.jpg",
        title: 'fourthlook',
        author: '',
        cols: 4,
    },
    {
        id: '10',
        img: "./closed/29.jpg",
        title: 'thirdlook',
        author: '',
        cols: 8,
    },
    {
        id: '11',
        img: "./closed/30.jpg",
        title: 'fourthlook',
        author: '',
        cols: 4,
    },
    {
        id: '12',
        img: "./closed/6.png",
        title: 'thirdlook',
        author: '',
        cols: 12,
    },
    {
        id: '13',
        img: "./closed/7.png",
        title: 'thirdlook',
        author: '',
        cols: 12,
    },
    {
        id: '14',
        img: "./closed/33.jpg",
        title: 'fourthlook',
        author: '',
        cols: 6,
    },
    {
        id: '15',
        img: "./closed/34.jpg",
        title: 'fourthlook',
        author: '',
        cols: 6,
    },
    {
        id: '16',
        img: "./closed/37.jpg",
        title: 'fourthlook',
        author: '',
        cols: 6,
    },
    {
        id: '17',
        img: "./closed/38.jpg",
        title: 'fourthlook',
        author: '',
        cols: 6,
    },
    {
        id: '18',
        img: "./closed/41.jpg",
        title: 'seventhlook',
        author: '',
        cols: 12,
    },
]

export const closedFeelingGallery2 = [
    {
        id: '19',
        img: "./closed/43.jpg",
        title: 'seventhlook',
        author: '',
        cols: 12,
        rows: 2,
    },
    {
        id: '20',
        img: "./closed/13.jpg",
        title: 'seventhlook',
        author: '',
        cols: 3,
    },
    {
        id: '21',
        img: "./closed/16.jpg",
        title: 'fourthlook',
        author: '',
        cols: 3,
    },
    {
        id: '22',
        img: "./closed/17.jpg",
        title: 'seventhlook',
        author: '',
        cols: 3,
    },
    {
        id: '23',
        img: "./closed/15.jpg",
        title: 'thirdlook',
        author: '',
        cols: 3,
    },
    {
        id: '24',
        img: "./closed/13.jpg",
        title: 'seventhlook',
        author: '',
        cols: 6,
    },
    {
        id: '25',
        img: "./closed/14.jpg",
        title: 'seventhlook',
        author: '',
        cols: 6,
    },
    {
        id: '26',
        img: "./closed/31.jpg",
        title: 'fourthlook',
        author: '',
        cols: 12,
    },
    {
        id: '27',
        img: "./closed/28.jpg",
        title: 'seventhlook',
        author: '',
        cols: 8,
    },
    {
        id: '28',
        img: "./closed/32.jpg",
        title: 'seventhlook',
        author: '',
        cols: 4,
    },
    {
        id: '29',
        img: "./closed/10.png",
        title: 'thirdlook',
        author: '',
        cols: 4,
    },
    {
        id: '30',
        img: "./closed/2.png",
        title: 'thirdlook',
        author: '',
        cols: 4,
    },
    {
        id: '31',
        img: "./closed/3.png",
        title: 'seventhlook',
        author: '',
        cols: 4,
    },
    {
        id: '32',
        img: "./closed/4.png",
        title: 'fourthlook',
        author: '',
        cols: 4,
    },
    {
        id: '33',
        img: "./closed/5.png",
        title: 'thirdlook',
        author: '',
        cols: 4,
    },
    {
        id: '34',
        img: "./closed/8.png",
        title: 'seventhlook',
        author: '',
        cols: 4,
    },
    {
        id: '35',
        img: "./closed/35.jpg",
        title: 'fourthlook',
        author: '',
        cols: 6,
    },
    {
        id: '36',
        img: "./closed/36.jpg",
        title: 'fourthlook',
        author: '',
        cols: 6,
    },
    {
        id: '37',
        img: "./closed/39.jpg",
        title: 'fourthlook',
        author: '',
        cols: 6,
    },
    {
        id: '38',
        img: "./closed/40.jpg",
        title: 'fourthlook',
        author: '',
        cols: 6,
    },
    {
        id: '39',
        img: "./closed/44.jpg",
        title: 'seventhlook',
        author: '',
        cols: 12,
    },
]