export const peaceGallery = [
    {
        img: "./peace/1.jpg",
        title: 'thirdlook',
        author: '',
        cols: 4,
    },
    {
        img: "./peace/2.jpg",
        title: 'thirdlook',
        author: '',
        cols: 4,
    },
    {
        img: "./peace/3.jpg",
        title: 'seventhlook',
        author: '',
        cols: 4,
    },
    {
        img: "./peace/4.jpg",
        title: 'fourthlook',
        author: '',
        cols: 4,
    },
    {
        img: "./peace/5.jpg",
        title: 'thirdlook',
        author: '',
        cols: 4,
    },
    {
        img: "./peace/6.jpg",
        title: 'seventhlook',
        author: '',
        cols: 4,
    },
    {
        img: "./peace/7.jpg",
        title: 'seventhlook',
        author: '',
        cols: 12,
    },
    {
        img: "./peace/8.jpg",
        title: 'thirdlook',
        author: '',
        cols: 8,
    },
    {
        img: "./peace/9.jpg",
        title: 'fourthlook',
        author: '',
        cols: 4,
    },
    {
        img: "./peace/10.jpg",
        title: 'thirdlook',
        author: '',
        cols: 8,
    },
    {
        img: "./peace/11.jpg",
        title: 'fourthlook',
        author: '',
        cols: 4,
    },
    {
        img: "./peace/12.jpg",
        title: 'thirdlook',
        author: '',
        cols: 12,
    },
    {
        img: "./peace/13.jpg",
        title: 'thirdlook',
        author: '',
        cols: 12,
    },
    {
        img: "./peace/25.jpg",
        title: 'fourthlook',
        author: '',
        cols: 6,
    },
    {
        img: "./peace/27.jpg",
        title: 'fourthlook',
        author: '',
        cols: 6,
    },
    {
        img: "./peace/30.jpg",
        title: 'fourthlook',
        author: '',
        cols: 6,
    },
    {
        img: "./peace/31.jpg",
        title: 'fourthlook',
        author: '',
        cols: 6,
    },
    {
        img: "./peace/24.jpg",
        title: 'seventhlook',
        author: '',
        cols: 12,
    },
]

export const peaceGallery2 = [
    {
        img: "./peace/14.jpg",
        title: 'seventhlook',
        author: '',
        cols: 12,
    },
    {
        img: "./peace/15.jpg",
        title: 'seventhlook',
        author: '',
        cols: 3,
    },
    {
        img: "./peace/16.jpg",
        title: 'fourthlook',
        author: '',
        cols: 3,
    },
    {
        img: "./peace/17.jpg",
        title: 'seventhlook',
        author: '',
        cols: 3,
    },
    {
        img: "./peace/18.jpg",
        title: 'thirdlook',
        author: '',
        cols: 3,
    },
    {
        img: "./peace/19.jpg",
        title: 'seventhlook',
        author: '',
        cols: 6,
    },
    {
        img: "./peace/20.jpg",
        title: 'seventhlook',
        author: '',
        cols: 6,
    },
    {
        img: "./peace/21.jpg",
        title: 'fourthlook',
        author: '',
        cols: 12,
    },
    {
        img: "./peace/22.jpg",
        title: 'seventhlook',
        author: '',
        cols: 8,
    },
    {
        img: "./peace/32.jpg",
        title: 'seventhlook',
        author: '',
        cols: 4,
    },
    {
        img: "./peace/33.jpg",
        title: 'thirdlook',
        author: '',
        cols: 4,
    },
    {
        img: "./peace/34.jpg",
        title: 'thirdlook',
        author: '',
        cols: 4,
    },
    {
        img: "./peace/35.jpg",
        title: 'seventhlook',
        author: '',
        cols: 4,
    },
    {
        img: "./peace/36.jpg",
        title: 'fourthlook',
        author: '',
        cols: 4,
    },
    {
        img: "./peace/37.jpg",
        title: 'thirdlook',
        author: '',
        cols: 4,
    },
    {
        img: "./peace/38.jpg",
        title: 'seventhlook',
        author: '',
        cols: 4,
    },
    {
        img: "./peace/39.jpg",
        title: 'fourthlook',
        author: '',
        cols: 6,
    },
    {
        img: "./peace/40.jpg",
        title: 'fourthlook',
        author: '',
        cols: 6,
    },
    {
        img: "./peace/28.jpg",
        title: 'fourthlook',
        author: '',
        cols: 6,
    },
    {
        img: "./peace/29.jpg",
        title: 'fourthlook',
        author: '',
        cols: 6,
    },
    {
        img: "./peace/23.jpg",
        title: 'seventhlook',
        author: '',
        cols: 12,
    },
]