export const peaceGallery = [
    {
        id: '1',
        img: "./peace/1.jpg",
        title: 'thirdlook',
        author: '',
        cols: 4,
    },
    {
        id: '2',
        img: "./peace/2.jpg",
        title: 'thirdlook',
        author: '',
        cols: 4,
    },
    {
        id: '3',
        img: "./peace/3.jpg",
        title: 'seventhlook',
        author: '',
        cols: 4,
    },
    {
        id: '4',
        img: "./peace/4.jpg",
        title: 'fourthlook',
        author: '',
        cols: 4,
    },
    {
        id: '5',
        img: "./peace/5.jpg",
        title: 'thirdlook',
        author: '',
        cols: 4,
    },
    {
        id: '6',
        img: "./peace/6.jpg",
        title: 'seventhlook',
        author: '',
        cols: 4,
    },
    {
        id: '7',
        img: "./peace/7.jpg",
        title: 'seventhlook',
        author: '',
        cols: 12,
    },
    {
        id: '8',
        img: "./peace/8.jpg",
        title: 'thirdlook',
        author: '',
        cols: 8,
    },
    {
        id: '9',
        img: "./peace/9.jpg",
        title: 'fourthlook',
        author: '',
        cols: 4,
    },
    {
        id: '10',
        img: "./peace/10.jpg",
        title: 'thirdlook',
        author: '',
        cols: 8,
    },
    {
        id: '11',
        img: "./peace/11.jpg",
        title: 'fourthlook',
        author: '',
        cols: 4,
    },
    {
        id: '12',
        img: "./peace/12.jpg",
        title: 'thirdlook',
        author: '',
        cols: 12,
    },
    {
        id: '13',
        img: "./peace/13.jpg",
        title: 'thirdlook',
        author: '',
        cols: 12,
    },
    {
        id: '14',
        img: "./peace/25.jpg",
        title: 'fourthlook',
        author: '',
        cols: 6,
    },
    {
        id: '15',
        img: "./peace/27.jpg",
        title: 'fourthlook',
        author: '',
        cols: 6,
    },
    {
        id: '16',
        img: "./peace/30.jpg",
        title: 'fourthlook',
        author: '',
        cols: 6,
    },
    {
        id: '17',
        img: "./peace/31.jpg",
        title: 'fourthlook',
        author: '',
        cols: 6,
    },
    {
        id: '18',
        img: "./peace/24.jpg",
        title: 'seventhlook',
        author: '',
        cols: 12,
    },
]

export const peaceGallery2 = [
    {
        id: '19',
        img: "./peace/14.jpg",
        title: 'seventhlook',
        author: '',
        cols: 12,
    },
    {
        id: '20',
        img: "./peace/15.jpg",
        title: 'seventhlook',
        author: '',
        cols: 3,
    },
    {
        id: '21',
        img: "./peace/16.jpg",
        title: 'fourthlook',
        author: '',
        cols: 3,
    },
    {
        id: '22',
        img: "./peace/17.jpg",
        title: 'seventhlook',
        author: '',
        cols: 3,
    },
    {
        id: '23',
        img: "./peace/18.jpg",
        title: 'thirdlook',
        author: '',
        cols: 3,
    },
    {
        id: '24',
        img: "./peace/19.jpg",
        title: 'seventhlook',
        author: '',
        cols: 6,
    },
    {
        id: '25',
        img: "./peace/20.jpg",
        title: 'seventhlook',
        author: '',
        cols: 6,
    },
    {
        id: '26',
        img: "./peace/21.jpg",
        title: 'fourthlook',
        author: '',
        cols: 12,
    },
    {
        id: '27',
        img: "./peace/22.jpg",
        title: 'seventhlook',
        author: '',
        cols: 8,
    },
    {
        id: '28',
        img: "./peace/32.jpg",
        title: 'seventhlook',
        author: '',
        cols: 4,
    },
    {
        id: '29',
        img: "./peace/33.jpg",
        title: 'thirdlook',
        author: '',
        cols: 4,
    },
    {
        id: '30',
        img: "./peace/34.jpg",
        title: 'thirdlook',
        author: '',
        cols: 4,
    },
    {
        id: '31',
        img: "./peace/35.jpg",
        title: 'seventhlook',
        author: '',
        cols: 4,
    },
    {
        id: '32',
        img: "./peace/36.jpg",
        title: 'fourthlook',
        author: '',
        cols: 4,
    },
    {
        id: '33',
        img: "./peace/37.jpg",
        title: 'thirdlook',
        author: '',
        cols: 4,
    },
    {
        id: '34',
        img: "./peace/38.jpg",
        title: 'seventhlook',
        author: '',
        cols: 4,
    },
    {
        id: '35',
        img: "./peace/39.jpg",
        title: 'fourthlook',
        author: '',
        cols: 6,
    },
    {
        id: '36',
        img: "./peace/40.jpg",
        title: 'fourthlook',
        author: '',
        cols: 6,
    },
    {
        id: '37',
        img: "./peace/28.jpg",
        title: 'fourthlook',
        author: '',
        cols: 6,
    },
    {
        id: '38',
        img: "./peace/29.jpg",
        title: 'fourthlook',
        author: '',
        cols: 6,
    },
    {
        id: '39',
        img: "./peace/23.jpg",
        title: 'seventhlook',
        author: '',
        cols: 12,
    },
]