export const seanceGallery = [
    {
        id: '1',
        img: "./seance/24.jpg",
        title: 'thirdlook',
        author: '',
        cols: 3,
    },
    {
        id: '2',
        img: "./seance/17.jpg",
        title: 'thirdlook',
        author: '',
        cols: 3,
    },
    {
        id: '3',
        img: "./seance/22.jpg",
        title: 'thirdlook',
        author: '',
        cols: 3,
    },
    {
        id: '4',
        img: "./seance/21.jpg",
        title: 'seventhlook',
        author: '',
        cols: 3,
    },
    {
        id: '5',
        img: "./seance/26.jpg",
        title: 'fourthlook',
        author: '',
        cols: 6,
    },
    {
        id: '6',
        img: "./seance/22.jpg",
        title: 'seventhlook',
        author: '',
        cols: 6,
    },
    {
        id: '7',
        img: "./seance/11.jpg",
        title: 'seventhlook',
        author: '',
        cols: 12,
        rows: 2,
    },
    {
        id: '8',
        img: "./seance/12.jpg",
        title: 'thirdlook',
        author: '',
        cols: 12,
        rows: 1,
    },
    {
        id: '9',
        img: "./seance/27.jpg",
        title: 'thirdlook',
        author: '',
        cols: 12,
    },
    {
        id: '10',
        img: "./seance/28.jpg",
        title: 'thirdlook',
        author: '',
        cols: 8,
    },
    {
        id: '11',
        img: "./seance/30.jpg",
        title: 'fourthlook',
        author: '',
        cols: 4,
    },
]

export const seanceGallery2 = [
    {
        id: '12',
        img: "./seance/25.jpg",
        title: 'seventhlook',
        author: '',
        cols: 12,
        rows: 2,
    },
    {
        id: '13',
        img: "./seance/12.jpg",
        title: 'seventhlook',
        author: '',
        cols: 3,
    },
    {
        id: '14',
        img: "./seance/1.jpg",
        title: 'fourthlook',
        author: '',
        cols: 3,
    },
    {
        id: '15',
        img: "./seance/2.jpg",
        title: 'seventhlook',
        author: '',
        cols: 3,
    },
    {
        id: '16',
        img: "./seance/3.jpg",
        title: 'thirdlook',
        author: '',
        cols: 3,
    },
    {
        id: '17',
        img: "./seance/4.jpg",
        title: 'seventhlook',
        author: '',
        cols: 6,
    },
    {
        id: '18',
        img: "./seance/6.jpg",
        title: 'seventhlook',
        author: '',
        cols: 6,
    },
    {
        id: '19',
        img: "./seance/11.jpg",
        title: 'fourthlook',
        author: '',
        cols: 12,
    },
    {
        id: '20',
        img: "./seance/30.jpg",
        title: 'seventhlook',
        author: '',
        cols: 4,
    },
    {
        id: '21',
        img: "./seance/31.jpg",
        title: 'seventhlook',
        author: '',
        cols: 8,
    },
    {
        id: '22',
        img: "./seance/27.jpg",
        title: 'seventhlook',
        author: '',
        cols: 8,
    },
    {
        id: '23',
        img: "./seance/34.jpg",
        title: 'seventhlook',
        author: '',
        cols: 4,
    },
]