export const virginiaCreeper = [
    {
        id: '1',
        img: "./virginia/1.jpg",
        title: 'firstlook',
        author: '',
        cols: 4,
        rows: 2,
    },
    {
        id: '2',
        img: "./virginia/0.jpg",
        title: 'secondlook',
        author: '',
        cols: 8,
        rows: 2,
    },
    {
        id: '3',
        img: "./virginia/5.jpg",
        title: 'firstlook',
        author: '',
        cols: 2,
        rows:1,
    },
    {
        id: '4',
        img: "./virginia/7.jpg",
        title: 'secondlook',
        author: '',
        cols: 2,
    },
    {
        id: '5',
        img: "./virginia/8.jpg",
        title: 'firstlook',
        author: '',
        cols: 2,
    },
    {
        id: '6',
        img: "./virginia/9.jpg",
        title: 'secondlook',
        author: '',
        cols: 2,
    },
    {
        id: '7',
        img: "./virginia/10.jpg",
        title: 'firstlook',
        author: '',
        cols: 2,
    },
    {
        id: '8',
        img: "./virginia/11.jpg",
        title: 'secondlook',
        author: '',
        cols: 2,
    },
    {
        id: '9',
        img: "./virginia/3.jpg",
        title: 'secondlook',
        author: '',
        cols: 8,
        rows: 2,
    },
    {
        id: '10',
        img: "./virginia/16.jpg",
        title: 'firstlook',
        author: '',
        cols: 4,
        rows: 2,
    },
    {
        id: '11',
        img: "./virginia/2.jpg",
        title: 'firstlook',
        author: '',
        cols: 2,
    },
    {
        id: '12',
        img: "./virginia/6.jpg",
        title: 'firstlook',
        author: '',
        cols: 2,
    },
    {
        id: '13',
        img: "./virginia/12.jpg",
        title: 'firstlook',
        author: '',
        cols: 2,
    },
    {
        id: '14',
        img: "./virginia/13.jpg",
        title: 'secondlook',
        author: '',
        cols: 2,
    },
    {
        id: '15',
        img: "./virginia/14.jpg",
        title: 'firstlook',
        author: '',
        cols: 2,
    },
    {
        id: '16',
        img: "./virginia/15.jpg",
        title: 'firstlook',
        author: '',
        cols: 2,
    },
];

